version: "3.3"

services:
  postgres:
    container_name: postgres-db
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=takai
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=just_sail_it
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql
    networks:
      dbnet:
        ipv4_address: 172.20.128.2
    restart: always
  minio:
    image: minio/minio
    container_name: minio-dev
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    networks:
      dbnet:
        ipv4_address: 172.20.128.3
    environment:
      MINIO_ROOT_USER: takai
      MINIO_ROOT_PASSWORD: 123456789
    command: server --console-address ":9001" /data

networks:
  dbnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
volumes:
  local_pgdata:
  minio_storage:
