export enum DB_E {
	DUPLICATE = '23505',
	UNDEFINED_COLUMN = '42703',
	UNKNOWN = 'UNKNOWN'
}

export enum AUTH_E {
	INVALID = 'INVALIDTOKEN',
	EXPIRE= 'EXPIRE',
	UNAUTHORIZE_UPDATE = 'UNAUTHORIZE_UPDATE',
	UNKNOWN = 'UNKNOWN'
}

export enum REQEST_E {
	EMPTY = 'EMPTY'
}

export enum SERVER_E {
	TIMEOUT = 'TIMEOUT'
}
